### ISSUE TITLE
pip install osaca fails

### ISSUE THREAD

**Issue by egonelbre** [RRZE-HPC/OSACA#13]
Installing via pip fails (on Windows and Mac):

```
c:\Python37>scripts\pip install osaca
Collecting osaca
  Using cached https://files.pythonhosted.org/packages/88/a5/2a81436fc6321f057e6d6a70369d0847d6c6ba48b9d70cbc16920846b288/osaca-0.2.0-py3-none-any.whl
Collecting pandas (from osaca)
  Using cached https://files.pythonhosted.org/packages/26/fc/d0509d445d2724fbc5f9c9a6fc9ce7da794873469739b6c94afc166ac2a2/pandas-0.23.4-cp37-cp37m-win32.whl
Collecting kerncraft (from osaca)
  Using cached https://files.pythonhosted.org/packages/0a/d0/7bead12116240d698e58ac54349f0a45c645fe3d9b8cc88ab0121b69da00/kerncraft-0.6.10.tar.gz
Collecting numpy (from osaca)
  Using cached https://files.pythonhosted.org/packages/2d/d4/ddfa53d27e2cdfef261b744df6e4b68134fc69b0d45ad8211e560178c852/numpy-1.15.1-cp37-none-win32.whl
Collecting pytz>=2011k (from pandas->osaca)
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Collecting python-dateutil>=2.5.0 (from pandas->osaca)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting ruamel.yaml<0.14.0,>=0.13.4 (from kerncraft->osaca)
  Using cached https://files.pythonhosted.org/packages/6d/00/061d150591d34065748857580735c4b42879a7dd3ebb75dde23671b60c26/ruamel.yaml-0.13.14.tar.gz
    Complete output from command python setup.py egg_info:
    Warning: 'keywords' should be a list, got type 'NoneType'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Egon\AppData\Local\Temp\pip-install-rn5n_nk5\ruamel.yaml\setup.py", line 854, in <module>
        main()
      File "C:\Users\Egon\AppData\Local\Temp\pip-install-rn5n_nk5\ruamel.yaml\setup.py", line 843, in main
        setup(**kw)
      File "c:\python37\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\python37\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python37\lib\site-packages\setuptools\dist.py", line 372, in __init__
        _Distribution.__init__(self, attrs)
      File "c:\python37\lib\distutils\dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "c:\python37\lib\distutils\dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "c:\python37\lib\distutils\dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable
```

**Comment by cod3monk** [comment]
This installation problem seems to emanate from `ruamel.yaml` and none of our packages. You should experience the same issue if you try to install the correct `ruamel.yaml` version standalone with `pip install ruamel.yaml<0.14.0,>=0.13.4`.

I checked the [`ruamel.yaml` issue tracker](https://bitbucket.org/ruamel/yaml/issues) and came across this: [0.4.12 fails to install with Python 3.7](https://bitbucket.org/ruamel/yaml/issues/207/0412-fails-to-install-with-python-37). This seems to indicate that the `ruamel.yaml` versions which `kerncraft` requires are incompatible with Python 3.7. I have opened a ticked here: RRZE-HPC/kerncraft#100

Until then, please use Python 3.6 to circumvent this issue.

**Comment by egonelbre** [comment]
Didn't work locally, also the tests in https://github.com/RRZE-HPC/kerncraft/pull/101/commits/fb40a07a269f8948e8fa53f794c1c414642b89cc with Python3.7

But, yes, Python 3.6 version did work.

**Comment by cod3monk** [comment]
> Didn't work locally, also the tests in [RRZE-HPC/kerncraft@fb40a07](https://github.com/RRZE-HPC/kerncraft/commit/fb40a07a269f8948e8fa53f794c1c414642b89cc) with Python3.7, thanks

python 3.7 is currently unsupported in travis, that's why I had to deactivate in the build matrix.

**Comment by egonelbre** [comment]
Ah, wait, I think it hasn't been updated on pip yet, hence it's still downloading the 0.6.10 version

**Comment by cod3monk** [comment]
Right, you will need to install from git until I update the package on pypi:
```
pip install git+https://github.com/RRZE-HPC/kerncraft.git
```
should to the trick.

**Comment by egonelbre** [comment]
Ah, thanks, yeah, works now.

Feel free to close, unless you want to keep it open for updating pip.
