### ISSUE TITLE
OSACA can't parse unknown instructions that don't have operands

### ISSUE THREAD

**Issue by ychen306** [RRZE-HPC/OSACA#32]
For example, it crashes when trying to analyze `cqto` with following messages:

```
Traceback (most recent call last):
  File "/Users/tom/workspace/OSACA/env/bin/osaca", line 11, in <module>
    load_entry_point('osaca==0.2.1', 'console_scripts', 'osaca')()
  File "/Users/tom/workspace/OSACA/env/lib/python3.7/site-packages/osaca-0.2.1-py3.7.egg/osaca/osaca.py", line 836, in main
    osaca = OSACA(args.arch, assembly)
  File "/Users/tom/workspace/OSACA/env/lib/python3.7/site-packages/osaca-0.2.1-py3.7.egg/osaca/osaca.py", line 408, in __init__
    self.inspect()
  File "/Users/tom/workspace/OSACA/env/lib/python3.7/site-packages/osaca-0.2.1-py3.7.egg/osaca/osaca.py", line 427, in inspect
    self.check_instr(line)
  File "/Users/tom/workspace/OSACA/env/lib/python3.7/site-packages/osaca-0.2.1-py3.7.egg/osaca/osaca.py", line 483, in check_instr
    tc = Testcase(mnemonic, list(reversed(param_list_types)), '32')
  File "/Users/tom/workspace/OSACA/env/lib/python3.7/site-packages/osaca-0.2.1-py3.7.egg/osaca/testcase.py", line 72, in __init__
    self.__define_operands()
  File "/Users/tom/workspace/OSACA/env/lib/python3.7/site-packages/osaca-0.2.1-py3.7.egg/osaca/testcase.py", line 134, in __define_operands
    if isinstance(operands[0], Register):
IndexError: list index out of range
```

**Comment by JanLJL** [comment]
Fixed in c1cf539.
Please keep in mind that you still have to add any new instruction to analyze into the database first.
