### ISSUE TITLE
Seemingly simple ARM instructions aren't recognized

### ISSUE THREAD

**Issue by mattgodbolt** [RRZE-HPC/OSACA#56]
Apologies if this is specific to the Compiler Explorer integration, but the simple input:

```
square(int):                             // @square(int)
        sub     sp, sp, #16                     // =16
        str     w0, [sp, #12]
        ldr     w8, [sp, #12]
        ldr     w9, [sp, #12]
        mul     w0, w8, w9
        add     sp, sp, #16                     // =16
        ret
```

Yields this error:

```
*-*-*-*-*-*-*-*-*-*-
8: 	.file	1 "/home/ce" "./example.cpp"
*-*-*-*-*-*-*-*-*-*-


Traceback (most recent call last):
  File "/opt/compiler-explorer/osaca-0.3.10/lib/python3.8/site-packages/osaca/osaca.py", line 262, in inspect
    parsed_code = parser.parse_file(code)
  File "/opt/compiler-explorer/osaca-0.3.10/lib/python3.8/site-packages/osaca/parser/base_parser.py", line 54, in parse_file
    asm_instructions.append(self.parse_line(line, i + 1 + start_line))
  File "/opt/compiler-explorer/osaca-0.3.10/lib/python3.8/site-packages/osaca/parser/parser_AArch64.py", line 286, in parse_line
    instruction_form[self.INSTRUCTION_ID] = result[self.INSTRUCTION_ID]
TypeError: 'NoneType' object is not subscriptable
```

which seems to be an unrecognized instruction? c.f. compiler-explorer/compiler-explorer#2319

**Comment by cod3monk** [comment]
exception fixed in 0.3.11, missing instructions will be added in next release
