### ISSUE TITLE
Parsing negative hex offsets fails

### ISSUE THREAD

**Issue by andreas-abel** [RRZE-HPC/OSACA#64]
Example: `add -0x1(%ebx),%eax`

Output:

```
Traceback (most recent call last):
  File "/home/andreas/.local/lib/python3.6/site-packages/osaca/parser/parser_x86att.py", line 255, in parse_line
    result = self.parse_instruction(line)
  File "/home/andreas/.local/lib/python3.6/site-packages/osaca/parser/parser_x86att.py", line 273, in parse_instruction
    result = self.instruction_parser.parseString(instruction, parseAll=True).asDict()
  File "/home/andreas/.local/lib/python3.6/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/home/andreas/.local/lib/python3.6/site-packages/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of text, found '-'  (at char 4), (line:1, col:5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andreas/.local/lib/python3.6/site-packages/osaca/osaca.py", line 270, in inspect
    parsed_code = parser.parse_file(code)
  File "/home/andreas/.local/lib/python3.6/site-packages/osaca/parser/base_parser.py", line 57, in parse_file
    asm_instructions.append(self.parse_line(line, i + 1 + start_line))
  File "/home/andreas/.local/lib/python3.6/site-packages/osaca/parser/parser_x86att.py", line 258, in parse_line
    'Could not parse instruction on line {}: {!r}'.format(line_number, line)
ValueError: Could not parse instruction on line 7: 'add -0x1(%ebx),%eax'
```

**Comment by andreas-abel** [comment]
This appears to be fixed in the current version in the repository. I was previously using the version obtained by `pip install --user osaca` (both report the version as 0.3.14 so I assumed they would be identical).

**Comment by JanLJL** [comment]
Hi @andreas-abel,
sorry for getting back to you only after such a long time.
We normally increase our version number together with the github tag and deploy this version to Pipy, sorry if this was unclear!
I assume I can close this issue?
