### ISSUE TITLE
Benchmark with movb fails on ICL

### ISSUE THREAD

**Issue by andreas-abel** [RRZE-HPC/OSACA#67]
The following benchmark leads to a TypeError on ICL. It works on other targets.

`echo 'movb $0x1,0x47(%rsp)' | osaca --arch ICL -`

Output:

```
Traceback (most recent call last):
  File "/usr/local/bin/osaca", line 11, in <module>
    load_entry_point('osaca==0.3.14', 'console_scripts', 'osaca')()
  File "/usr/local/lib/python3.6/dist-packages/osaca/osaca.py", line 387, in main
    run(args, output_file=args.out)
  File "/usr/local/lib/python3.6/dist-packages/osaca/osaca.py", line 339, in run
    inspect(args, output_file=output_file)
  File "/usr/local/lib/python3.6/dist-packages/osaca/osaca.py", line 293, in inspect
    semantics.add_semantics(kernel)
  File "/usr/local/lib/python3.6/dist-packages/osaca/semantics/arch_semantics.py", line 31, in add_semantics
    self.assign_tp_lt(instruction_form)
  File "/usr/local/lib/python3.6/dist-packages/osaca/semantics/arch_semantics.py", line 283, in assign_tp_lt
    else 0
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'
```

**Comment by JanLJL** [comment]
Should be fixed in 9a13e5c, feel free to re-open in case I missed something.
Thanks for helping finding those bugs!
