### ISSUE TITLE
Benchmark with xor fails on HSW

### ISSUE THREAD

**Issue by andreas-abel** [RRZE-HPC/OSACA#69]
The following benchmark leads to a KeyError on HSW. It works on other targets.

`echo 'xor 0x12(%rsi),%al' | osaca --arch HSW -` 

Output:

```
Traceback (most recent call last):
  File "/usr/local/bin/osaca", line 11, in <module>
    load_entry_point('osaca==0.3.14', 'console_scripts', 'osaca')()
  File "/usr/local/lib/python3.6/dist-packages/osaca/osaca.py", line 387, in main
    run(args, output_file=args.out)
  File "/usr/local/lib/python3.6/dist-packages/osaca/osaca.py", line 339, in run
    inspect(args, output_file=output_file)
  File "/usr/local/lib/python3.6/dist-packages/osaca/osaca.py", line 293, in inspect
    semantics.add_semantics(kernel)
  File "/usr/local/lib/python3.6/dist-packages/osaca/semantics/arch_semantics.py", line 31, in add_semantics
    self.assign_tp_lt(instruction_form)
  File "/usr/local/lib/python3.6/dist-packages/osaca/semantics/arch_semantics.py", line 215, in assign_tp_lt
    operands.index(self._create_reg_wildcard())
  File "/usr/local/lib/python3.6/dist-packages/osaca/parser/parser_x86att.py", line 445, in get_reg_type
    if self.is_gpr(register):
  File "/usr/local/lib/python3.6/dist-packages/osaca/parser/parser_x86att.py", line 429, in is_gpr
    if self.is_basic_gpr(register):
  File "/usr/local/lib/python3.6/dist-packages/osaca/parser/parser_x86att.py", line 419, in is_basic_gpr
    any(char.isdigit() for char in register['name'])
  File "/home/andreas/.local/lib/python3.6/site-packages/ruamel/yaml/comments.py", line 753, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'name'
```

**Comment by cod3monk** [comment]
fixed in 0c5ac26.
Thanks for reporting!
