### ISSUE TITLE
Hex immediate are not recognized.

### ISSUE THREAD

**Issue by mlomonaco** [RRZE-HPC/OSACA#74]
I am using OSACA on godbolt.org and I noticed that on ARM assembly (GAS) immediates with 0x prefix are not converted correctly.
Like ```    sub	sp, sp, #0x3e0``` gives the following error:
```
OSACA (0.4.0) (Editor #1, Compiler #1) Analysis
OSACA (0.4.0)
Compiler options...
123
<Compilation failed>

# For more information see the output window
OSACA (0.4.0) - 14008ms
#1 with OSACA (0.4.0)
Traceback (most recent call last):
  File "/opt/compiler-explorer/osaca-0.4.0/bin/osaca", line 11, in <module>
    load_entry_point('osaca==0.4.0', 'console_scripts', 'osaca')()
  File "/opt/compiler-explorer/osaca-0.4.0/lib/python3.8/site-packages/osaca/osaca.py", line 397, in main
    run(args, output_file=args.out)
  File "/opt/compiler-explorer/osaca-0.4.0/lib/python3.8/site-packages/osaca/osaca.py", line 346, in run
    inspect(args, output_file=output_file)
  File "/opt/compiler-explorer/osaca-0.4.0/lib/python3.8/site-packages/osaca/osaca.py", line 306, in inspect
    kernel_graph = KernelDG(kernel, parser, machine_model, semantics)
  File "/opt/compiler-explorer/osaca-0.4.0/lib/python3.8/site-packages/osaca/semantics/kernel_dg.py", line 18, in __init__
    self.dg = self.create_DG(self.kernel)
  File "/opt/compiler-explorer/osaca-0.4.0/lib/python3.8/site-packages/osaca/semantics/kernel_dg.py", line 52, in create_DG
    for dep, dep_flags in self.find_depending(instruction_form, kernel[i + 1 :]):
  File "/opt/compiler-explorer/osaca-0.4.0/lib/python3.8/site-packages/osaca/semantics/kernel_dg.py", line 191, in find_depending
    register_changes = self._update_reg_changes(instruction_form)
  File "/opt/compiler-explorer/osaca-0.4.0/lib/python3.8/site-packages/osaca/semantics/kernel_dg.py", line 244, in _update_reg_changes
    for reg, change in self.arch_sem.get_reg_changes(iform, only_postindexed).items():
  File "/opt/compiler-explorer/osaca-0.4.0/lib/python3.8/site-packages/osaca/semantics/isa_semantics.py", line 197, in get_reg_changes
    operand_state[operand_name] = {'value': int(o["immediate"]["value"])}
ValueError: invalid literal for int() with base 10: '0x3e0'
Compiler returned: 1
```

**Comment by JanLJL** [comment]
Hi @mlomonaco,
thanks for reporting, this issue is already known and already fixed in the more recent versions of OSACA (>=0.4.1) .
The Compiler Explorer will be updated soon with the fixed version :)

**Comment by JanLJL** [comment]
OSACA v0.4.2 is now live on godbolt

**Comment by mlomonaco** [comment]
Thanks for the rapid action! Nonetheless 0.4.2 on Compiler Explorer seems to have still the problem (maybe it reappeared from 0.4.1 to 0.4.2)?
```
#1 with OSACA (0.4.2)
Traceback (most recent call last):
  File "/opt/compiler-explorer/osaca-0.4.2/bin/osaca", line 8, in <module>
    sys.exit(main())
  File "/opt/compiler-explorer/osaca-0.4.2/lib/python3.8/site-packages/osaca/osaca.py", line 411, in main
    run(args, output_file=args.out)
  File "/opt/compiler-explorer/osaca-0.4.2/lib/python3.8/site-packages/osaca/osaca.py", line 360, in run
    inspect(args, output_file=output_file)
  File "/opt/compiler-explorer/osaca-0.4.2/lib/python3.8/site-packages/osaca/osaca.py", line 319, in inspect
    kernel_graph = KernelDG(kernel, parser, machine_model, semantics, args.lcd_timeout)
  File "/opt/compiler-explorer/osaca-0.4.2/lib/python3.8/site-packages/osaca/semantics/kernel_dg.py", line 26, in __init__
    self.dg = self.create_DG(self.kernel)
  File "/opt/compiler-explorer/osaca-0.4.2/lib/python3.8/site-packages/osaca/semantics/kernel_dg.py", line 69, in create_DG
    for dep, dep_flags in self.find_depending(instruction_form, kernel[i + 1 :]):
  File "/opt/compiler-explorer/osaca-0.4.2/lib/python3.8/site-packages/osaca/semantics/kernel_dg.py", line 256, in find_depending
    register_changes = self._update_reg_changes(instruction_form)
  File "/opt/compiler-explorer/osaca-0.4.2/lib/python3.8/site-packages/osaca/semantics/kernel_dg.py", line 309, in _update_reg_changes
    for reg, change in self.arch_sem.get_reg_changes(iform, only_postindexed).items():
  File "/opt/compiler-explorer/osaca-0.4.2/lib/python3.8/site-packages/osaca/semantics/isa_semantics.py", line 200, in get_reg_changes
    operand_state[operand_name] = {'value': int(o["immediate"]["value"])}
ValueError: invalid literal for int() with base 10: '0x3e0'
Compiler returned: 1```

**Comment by JanLJL** [comment]
I can reproduce the error on godbolt, not locally though.
Sorry for this, I will have a deeper look into it

**Comment by JanLJL** [comment]
Hi @mlomonaco,

I changed the general handling of immediates and tested both the standalone OSACA and the integration in godbolt with my local version (running the same Python version as godbolt). I am still unsure what exactly created the error but I hope it will be fixed by this.

Should be resolved as soon as [`compiler-explorer`'s PR #2656](https://github.com/compiler-explorer/compiler-explorer/pull/2656) is live.

**Comment by mlomonaco** [comment]
Thanks a ton! It looks working good.
