### ISSUE TITLE
Bug with working with A64FX assembly code.

### ISSUE THREAD

**Issue by v0dro** [RRZE-HPC/OSACA#75]
I am trying to test OSACA by trying to measure the latencies of my own STREAM TRIAD code written using SVE instructions for the A64FX chip (used in the FUGAKU supercomputer) and am getting a bug in the master branch. The assembly code I'm using is as follows:
``` asm

// OSACA-BEGIN
.LBB0_2:
	.loc	1 14 45
	add	x8, x8, #1
	.loc	1 15 14
	ld1d	{ z1.d }, p0/z, [x1]
	.loc	1 16 14
	ld1d	{ z2.d }, p0/z, [x2]
	.loc	1 17 14
	fmla	z1.d, p0/m, z0.d, z2.d
	.loc	1 21 11
	add	x1, x1, #64
	.loc	1 22 11
	add	x2, x2, #64
	.loc	1 18 9
	st1d	{ z1.d }, p0, [x0]
	.loc	1 20 11
	add	x0, x0, #64
	.loc	1 14 5
	cmp	x9, x8
	b.hi	.LBB0_2
// OSACA-END
```

I use the following command with this file (called `test.S`):

```
osaca --arch A64FX test.S
```

.. and am getting the following error:

```
Traceback (most recent call last):
  File "/Users/sameer/opt/anaconda3/bin/osaca", line 33, in <module>
    sys.exit(load_entry_point('osaca==0.4.3', 'console_scripts', 'osaca')())
  File "/Users/sameer/opt/anaconda3/lib/python3.8/site-packages/osaca/osaca.py", line 411, in main
    run(args, output_file=args.out)
  File "/Users/sameer/opt/anaconda3/lib/python3.8/site-packages/osaca/osaca.py", line 360, in run
    inspect(args, output_file=output_file)
  File "/Users/sameer/opt/anaconda3/lib/python3.8/site-packages/osaca/osaca.py", line 298, in inspect
    raise e
  File "/Users/sameer/opt/anaconda3/lib/python3.8/site-packages/osaca/osaca.py", line 284, in inspect
    parsed_code = parser.parse_file(code)
  File "/Users/sameer/opt/anaconda3/lib/python3.8/site-packages/osaca/parser/base_parser.py", line 58, in parse_file
    asm_instructions.append(self.parse_line(line, i + 1 + start_line))
  File "/Users/sameer/opt/anaconda3/lib/python3.8/site-packages/osaca/parser/parser_AArch64.py", line 294, in parse_line
    result = self.parse_instruction(line)
  File "/Users/sameer/opt/anaconda3/lib/python3.8/site-packages/osaca/parser/parser_AArch64.py", line 316, in parse_instruction
    operands += self.process_operand(result["operand1"])
TypeError: 'NoneType' object is not iterable
```

Any ideas on what might be going wrong?

The C++ code I use for generating the assembly is as follows (compilation options are `FCC -Nclang -O3 -Ofast -S triad_sve.cpp -o triad_sve.S` for the FUJITSU compiler.

``` cpp

#include <cstdlib>
#include <cassert>
#include <iostream>
#include <arm_sve.h>
#include <arm_acle.h>

// #define VERIFY

void simd_kernel(double *A, double *B, double *C, double scalar, int size) {
    svfloat64_t z0, z1, z2;

    z0 = svdup_n_f64(scalar);

    for (int  i = 0; i < size / svcntd(); i += 1) {
        z1 = svld1(svptrue_b64(), B);
        z2 = svld1(svptrue_b64(), C);
        z1 = svmla_m(svptrue_b64(), z1, z0, z2);
        svst1(svptrue_b64(), A, z1);

        A += 8;
        B += 8;
        C += 8;
    }
}

#ifdef VERIFY
void kernel(double *A, double *B, double *C, double scalar, int size) {
    for (int  i = 0; i < size; i++) {
        A[i] = B[i] + scalar * C[i];
    }
}
#endif

int main(int argc, char const *argv[])
{
    double *A, *B, *C;
#ifdef VERIFY
    double *A_copy;
#endif
    int size;
    double scalar = 2.0;

    if (argc > 1) {
        size = atoi(argv[1]);
    }
    else {
        size = 1024;
    }

    assert(size % 8 == 0);

    A = (double*)malloc(sizeof(double) * size);
#ifdef VERIFY
    A_copy = (double*)malloc(sizeof(double) * size);
#endif
    B = (double*)malloc(sizeof(double) * size);
    C = (double*)malloc(sizeof(double) * size);

    for (int i = 0; i < size; ++i) {
        A[i] = 0.0;
#ifdef VERIFY
        A_copy[i] = 0.0;
#endif
        B[i] = 1.0;
        C[i] = rand();
    }

    simd_kernel(A, B, C, scalar, size);

#ifdef VERIFY
    kernel(A_copy, B, C, scalar, size);
    for (int i = 0; i < size; ++i) {
        assert(A[i] == A_copy[i]);
    }
    free(A_copy);
#endif

    free(A);
    free(B);
    free(C);

    return 0;
}
```

**Comment by v0dro** [comment]
Ping!

**Comment by JanLJL** [comment]
Hi @v0dro,
I'm terribly sorry no one got back to you so far!
Thanks for the detailed explanation, I can reproduce the bug and will commit a fix ASAP

**Comment by JanLJL** [comment]
Hi @v0dro,
unfortunately, this bugs was introduced by ourselves in version 0.4.2 by adding other features, apologies for that.
Please check out 090c24ade15de0307ae3fff16562b9c13589cbf0 or [OSACA v0.4.4](https://pypi.org/project/osaca/) and let me know in case you still face the problem!

**Comment by v0dro** [comment]
I tried installing 0.4.4 from pip and now get this error (I have installed ruamel with `pip install ruamel.yaml`):
```
(base) ➜  osaca git:(master) osaca --arch A64FX exn.S
Traceback (most recent call last):
  File "/home/sameer/anaconda3/bin/osaca", line 5, in <module>
    from osaca.osaca import main
  File "/home/sameer/anaconda3/lib/python3.8/site-packages/osaca/osaca.py", line 10, in <module>
    from osaca.db_interface import import_benchmark_output, sanity_check
  File "/home/sameer/anaconda3/lib/python3.8/site-packages/osaca/db_interface.py", line 10, in <module>
    import ruamel.yaml
ModuleNotFoundError: No module named 'ruamel'
```

**Comment by JanLJL** [comment]
Hi @v0dro,
it looks like you have a corrupt database file.
Have you edited any architecture DB or ISA DB and might missed an indentation, have a typo, etc.?

If not, try to make sure all old databases are removed, both in `~/.osaca/data` and your installation path (`/home/sameer/anaconda3/lib/python3.8/site-packages/osaca/osaca/data`), also take care of the cached files starting with a dot.

Hope this helps! Feel free to reopen if you could not succeed.
