### ISSUE TITLE
Python version clarification

### ISSUE THREAD

**Issue by mattgodbolt** [RRZE-HPC/OSACA#9]
Running `osaca` fails with python 2.7 yields

```
$ osaca --help
Traceback (most recent call last):
  File "/home/mgodbolt/apps/miniconda/envs/osaca/bin/osaca", line 11, in <module>
    load_entry_point('osaca==0.1', 'console_scripts', 'osaca')()
  File "/home/mgodbolt/apps/miniconda/envs/osaca/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mgodbolt/apps/miniconda/envs/osaca/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2687, in load_entry_point
    return ep.load()
  File "/home/mgodbolt/apps/miniconda/envs/osaca/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2341, in load
    return self.resolve()
  File "/home/mgodbolt/apps/miniconda/envs/osaca/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2347, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/mnt/data/apps/miniconda/envs/osaca/lib/python2.7/site-packages/osaca-0.1-py2.7.egg/osaca/osaca.py", line 54
    print('Copying files in user directory...', file=self.file_output, end='')
                                                    ^
SyntaxError: invalid syntax
```

It was installed without issue in a `conda` container created with `conda create -n osaca python=2.7`, and then `python ./setup.py install`

Judging from the error, it looks like Python 3 is the minimum requirement. The installer should check the python version, if this is the case, or the `print()` call should be a Python 2.7 `print` statement if 2.7 is supported.

**Comment by mattgodbolt** [comment]
NB: osaca installs and runs under python 3

**Comment by cod3monk** [comment]
Thank you for reporting this issue. Python >= 3.5 has always been an requirement, but was not set as such in the `setup.py`.

**Comment by mattgodbolt** [comment]
Thank you for this! I'm excited to have an OSS alternative to IACA. I'm hoping we can get a visualization for this into [Compiler Explorer](https://godbolt.org/).

**Comment by cod3monk** [comment]
That sounds like a very useful application of OSACA. I'm not sure it is up to the job yet, but we plan on extending and stabilizing features in the near future, with a continued focus on numeric kernels.
